project:
  type: website
  output-dir: docs

website:
  
  title: "PratiqueR"
  
  navbar:
    
    background: success
  
    left:
      - href: index.qmd
        text: Accueil
      - href: exercice.qmd
        text: Exercice
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact
        
    right: 
      - icon: github
        href: https://github.com/PratiqueR
      - icon: envelope
        href: mailto:pratiquerpro@outlook.com
        
  sidebar:
        style: "docked"
        search: true
        contents:
          - text: "Qu'est ce que R ?"
            href: autre/presentation_R.qmd
          - text: "Bonne pratiques"
            href: autre/bonne_pratique.qmd
            
          - section: "Fonctions R"
            contents:
                
              - section: "Fonction d'aggrégation"
                contents:
                    - fonctions/agregation/somme.qmd
                    - fonctions/agregation/minimum.qmd
                    - fonctions/agregation/maximum.qmd
                    - fonctions/agregation/moyenne.qmd
                    - fonctions/agregation/mediane.qmd
                    - fonctions/agregation/sd.qmd
                    - fonctions/agregation/variance.qmd
                    - fonctions/agregation/prod.qmd
                    - fonctions/agregation/length.qmd
                    - fonctions/agregation/range.qmd
                    - fonctions/agregation/summary.qmd
                    - fonctions/agregation/table.qmd
                    - fonctions/agregation/quantile.qmd
            
          - section: "Quarto"
            contents:
          - section: "Rmarkdown"
            contents:
          - section: "API"
            contents:
          - section: "Git et Github"
            contents:


  
  page-footer: "Copyright 2025, PratiqueR" 

format:
  html:
    theme: 
        light: default
        dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

