project:
  type: website
  output-dir: docs

website:
  
  title: "PratiqueR"
  
  navbar:
    
    background: success
  
    left:
      - href: index.qmd
        text: Accueil
      - href: exercice.qmd
        text: Exercice
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact
        
    right: 
      - icon: youtube
        href: https://youtube/PratiqueR
      - icon: github
        href: https://github.com/PratiqueR
      - icon: envelope
        href: mailto:pratiquerpro@outlook.com
        
  sidebar:
        style: "docked"
        search: true
        contents:
          - text: "Qu'est ce que R ?"
            href: pages/presentation_R.qmd
            
          - text: "Installation et Configuration"
            href: pages/installation.qmd
            
          - text: "Bonne pratiques"
            href: pages/bonne_pratique.qmd
            
            
            
          - section: "Fonctions R"
            contents:
                
              - section: "Gestions de fichiers"
                contents:
                
              - section: "Aggrégation"
                contents:
                    - fonctions/agregation/somme.qmd
                    - fonctions/agregation/minimum.qmd
                    - fonctions/agregation/maximum.qmd
                    - fonctions/agregation/moyenne.qmd
                    - fonctions/agregation/mediane.qmd
                    - fonctions/agregation/sd.qmd
                    - fonctions/agregation/variance.qmd
                    - fonctions/agregation/prod.qmd
                    - fonctions/agregation/length.qmd
                    - fonctions/agregation/range.qmd
                    - fonctions/agregation/summary.qmd
                    - fonctions/agregation/table.qmd
                    - fonctions/agregation/quantile.qmd
          
              - text: "Visualisation"
                href: fonctions/visualisation.qmd
                 
              - section: "Manipulation de données"
                contents:
                    - fonctions/manipulation/subset.qmd
                    - fonctions/manipulation/merge.qmd
                    - fonctions/manipulation/cbind.qmd
                    - fonctions/manipulation/rbind.qmd
                    - fonctions/manipulation/apply.qmd
                    - fonctions/manipulation/lapply.qmd
                    - fonctions/manipulation/sapply.qmd
                    - fonctions/manipulation/tapply.qmd
                    - fonctions/manipulation/sort.qmd
                    - fonctions/manipulation/order.qmd
                    - fonctions/manipulation/split.qmd
                    - fonctions/manipulation/transform.qmd
                    - fonctions/manipulation/rep.qmd
                    - fonctions/manipulation/seq.qmd
                    
              - section: "Tests statistiques"
                contents:
                    - fonctions/test/
                    - fonctions/test/
          
          - section: "Packages"
            contents:  
          - section: "Machine Learning"
            contents:
          - section: "Deep Learning"
            contents:
          - section: "Cartographie"
            contents:
          - section: "Shiny"
            contents:
          - section: "Quarto"
            contents:
                    - pages/quarto/presentation_quarto.qmd
          - text: "Rmarkdown"
            href: pages/rmarkdown.qmd
          - text: "Web scraping"
            href: pages/webscraping.qmd
          - section: "API"
            contents:
          - section: "Git et Github"
            contents:


  
  page-footer: "Copyright 2025, PratiqueR" 

format:
  html:
    theme: 
        light: default
        dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

