project:
  type: website

website:
  
  title: "PratiqueR"
  
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: exercice.qmd
        text: Exercice
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

