project:
  type: website
  output-dir: docs

website:
  
  title: "PratiqueR"
  
  navbar:
  
    left:
      - href: index.qmd
        text: Accueil
      - href: exercice.qmd
        text: Exercice
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact
        
    right: 
      - icon: github
        href: https://github.com/PratiqueR
      - icon: envelope
        href: mailto:pratiquerpro@outlook.com
        
  sidebar:
        style: "docked"
        background: light
        search: true
        contents:
          - text: "Qu'est ce que R ?"
            href: presentationR.qmd
            

        

  
  page-footer: "Copyright 2025, PratiqueR" 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

